# Generated by Django 4.2.7 on 2025-09-30 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="status_updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Last time the project status was updated"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="actual_hours",
            field=models.PositiveIntegerField(
                default=0, help_text="Actual hours spent on this project"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="priority",
            field=models.CharField(
                choices=[("low", "Low"), ("medium", "Medium"), ("high", "High")],
                default="medium",
                help_text="Project priority level",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("web_development", "Website Development"),
                    ("mobile_app", "Mobile Application"),
                    ("operations_system", "Operations Management System"),
                    ("portal", "Portal Development"),
                    ("audit", "System Audit"),
                ],
                help_text="Type of service we are providing",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="status",
            field=models.CharField(
                choices=[
                    ("lead", "Lead"),
                    ("quoted", "Quoted"),
                    ("approved", "Approved"),
                    ("planning", "Planning"),
                    ("development", "Development"),
                    ("testing", "Testing"),
                    ("client_review", "Client Review"),
                    ("completed", "Completed"),
                    ("on_hold", "On Hold"),
                ],
                default="lead",
                help_text="Current status of the project",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="StatusTransition",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "from_status",
                    models.CharField(
                        help_text="Previous status of the project", max_length=50
                    ),
                ),
                (
                    "to_status",
                    models.CharField(
                        help_text="New status of the project", max_length=50
                    ),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        auto_now_add=True, help_text="When the status change occurred"
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True, help_text="Reason for the status change"
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Additional notes about the status change"
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project that underwent status change",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_transitions",
                        to="core.project",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who made the status change",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_changes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Status Transition",
                "verbose_name_plural": "Status Transitions",
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["project", "timestamp"],
                        name="core_status_project_d85882_idx",
                    ),
                    models.Index(
                        fields=["timestamp"], name="core_status_timesta_195a24_idx"
                    ),
                    models.Index(
                        fields=["from_status", "to_status"],
                        name="core_status_from_st_d056f9_idx",
                    ),
                ],
            },
        ),
    ]
