# Generated by Django 4.2.7 on 2025-09-30 19:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_auto_20250930_1832"),
    ]

    operations = []
