# Generated by Django 4.2.7 on 2025-09-30 19:14

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_auto_20250930_1908"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="documenttemplate",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Document Template",
                "verbose_name_plural": "Document Templates",
            },
        ),
        migrations.RemoveIndex(
            model_name="documentinstance",
            name="core_docume_project_87f2ae_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentinstance",
            name="core_docume_templat_ab7f5c_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentinstance",
            name="core_docume_status_4ba2d9_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentinstance",
            name="core_docume_documen_f55e34_idx",
        ),
        migrations.RemoveIndex(
            model_name="documenttemplate",
            name="core_docume_documen_fed358_idx",
        ),
        migrations.RemoveIndex(
            model_name="documenttemplate",
            name="core_docume_status_6a8c71_idx",
        ),
        migrations.RemoveIndex(
            model_name="documenttemplate",
            name="core_docume_is_curr_b0ebd5_idx",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="approval_date",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="client_approval_date",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="client_feedback",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="document_name",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="file_format",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="file_path",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="file_size",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="rendered_content",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="requires_revision",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="review_date",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="reviewed_by",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="sent_to_client_date",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="superseded_by",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="template_version",
        ),
        migrations.RemoveField(
            model_name="documentinstance",
            name="version_number",
        ),
        migrations.AddField(
            model_name="documentinstance",
            name="document_number",
            field=models.CharField(
                blank=True, help_text="Document number or reference", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="documentinstance",
            name="document_title",
            field=models.CharField(
                default="Untitled Document",
                help_text="Title of this specific document instance",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="documentinstance",
            name="generated_pdf",
            field=models.FileField(
                blank=True,
                help_text="Generated PDF file",
                null=True,
                upload_to="documents/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["pdf"]
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="documentinstance",
            name="signed_at",
            field=models.DateTimeField(
                blank=True, help_text="When this document was signed", null=True
            ),
        ),
        migrations.AddField(
            model_name="documentinstance",
            name="signed_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who signed this document",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="signed_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="content",
            field=models.TextField(
                default="<html><body><h1>Template Content</h1><p>Template content goes here.</p></body></html>",
                help_text="HTML template content with Django template syntax",
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this template",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_document_templates",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="documenttemplate",
            name="template_type",
            field=models.CharField(
                choices=[
                    ("INTAKE", "Intake Document"),
                    ("ACCEPTANCE", "Acceptance Document"),
                    ("CHANGE", "Change Request Document"),
                    ("HANDOVER", "Handover Document"),
                    ("LEGAL", "Legal Document"),
                ],
                default="INTAKE",
                help_text="Type of document this template generates",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="documentinstance",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who generated this document",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documentinstance",
            name="filled_data",
            field=models.JSONField(
                default=dict, help_text="Data used to fill the template"
            ),
        ),
        migrations.AlterField(
            model_name="documentinstance",
            name="status",
            field=models.CharField(
                choices=[
                    ("GENERATED", "Generated"),
                    ("SIGNED", "Signed"),
                    ("ARCHIVED", "Archived"),
                ],
                default="GENERATED",
                help_text="Current status of this document",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="documentinstance",
            name="template",
            field=models.ForeignKey(
                help_text="Template used to generate this document",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="instances",
                to="core.documenttemplate",
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="description",
            field=models.TextField(
                blank=True, help_text="Description of what this template is used for"
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="name",
            field=models.CharField(
                default="Untitled Template",
                help_text="Human-readable name for this template",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="optional_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of optional field names for this template",
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="required_fields",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="List of required field names for this template",
            ),
        ),
        migrations.AlterField(
            model_name="documenttemplate",
            name="status",
            field=models.CharField(
                choices=[
                    ("DRAFT", "Draft"),
                    ("PUBLISHED", "Published"),
                    ("ARCHIVED", "Archived"),
                ],
                default="DRAFT",
                help_text="Current status of this template",
                max_length=20,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documenttemplate",
            unique_together={("name", "version")},
        ),
        migrations.AddIndex(
            model_name="documentinstance",
            index=models.Index(
                fields=["template", "project"], name="core_docume_templat_7da45a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentinstance",
            index=models.Index(
                fields=["status", "created_at"], name="core_docume_status_4ad28a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentinstance",
            index=models.Index(
                fields=["project", "created_at"], name="core_docume_project_405893_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentinstance",
            index=models.Index(
                fields=["document_number"], name="core_docume_documen_69590f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["template_type", "status"],
                name="core_docume_templat_d8671d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(
                fields=["status", "created_at"], name="core_docume_status_901c1d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documenttemplate",
            index=models.Index(fields=["name"], name="core_docume_name_441f80_idx"),
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="applicable_service_types",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="document_type",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="is_current_version",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="previous_version",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="template_content",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="template_format",
        ),
        migrations.RemoveField(
            model_name="documenttemplate",
            name="usage_count",
        ),
    ]
