# Generated by Django 4.2.7 on 2025-09-30 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_populate_sample_templates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documentinstance",
            name="project",
            field=models.ForeignKey(
                blank=True,
                help_text="Project this document belongs to",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="core.project",
            ),
        ),
    ]
