# Generated by Django 4.2.7 on 2025-09-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_alter_documentinstance_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="acknowledgment",
            field=models.JSONField(
                blank=True, default=dict, help_text="Acknowledgment and signature data"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="additional_notes",
            field=models.TextField(
                blank=True, help_text="Additional notes and requirements"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="address",
            field=models.TextField(
                blank=True, help_text="Complete address of the school"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="contact_person",
            field=models.CharField(
                blank=True,
                help_text="Primary contact person at the school",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="content_availability",
            field=models.BooleanField(
                default=False, help_text="Whether content is readily available"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="current_website",
            field=models.URLField(blank=True, help_text="Current website URL if any"),
        ),
        migrations.AddField(
            model_name="client",
            name="design_preferences",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Design preferences and requirements",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="email",
            field=models.EmailField(
                blank=True, help_text="Primary email address", max_length=254
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="logo_colors",
            field=models.JSONField(
                blank=True, default=dict, help_text="Preferred logo colors and branding"
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="maintenance_plan",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="Maintenance and support plan preferences",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="number_of_staff",
            field=models.IntegerField(
                blank=True, help_text="Total number of staff members", null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="number_of_students",
            field=models.IntegerField(
                blank=True, help_text="Total number of students", null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="phone_whatsapp",
            field=models.CharField(
                blank=True, help_text="Phone number or WhatsApp contact", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="pilot_end_date",
            field=models.DateField(
                blank=True, help_text="Expected pilot project end date", null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="pilot_scope_features",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Selected pilot scope features and modules",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="pilot_start_date",
            field=models.DateField(
                blank=True, help_text="Preferred pilot project start date", null=True
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="project_purpose",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Project purposes and goals (multiple choice)",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="project_type",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Selected project types (multiple choice)",
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="role_position",
            field=models.CharField(
                blank=True,
                help_text="Role or position of the contact person",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="school_name",
            field=models.CharField(
                blank=True,
                help_text="Name of the school or educational institution",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="timeline_preference",
            field=models.CharField(
                blank=True,
                choices=[
                    ("asap", "ASAP"),
                    ("1_month", "Within 1 Month"),
                    ("3_months", "Within 3 Months"),
                    ("6_months", "Within 6 Months"),
                    ("flexible", "Flexible"),
                ],
                help_text="Timeline preference for project start",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="client",
            name="token_commitment_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Token commitment fee amount",
                max_digits=10,
                null=True,
            ),
        ),
    ]
