# Generated by Django 4.2.7 on 2025-09-30 21:54

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0009_client_acknowledgment_client_additional_notes_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotAcceptance",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "acceptance_status",
                    models.CharField(
                        choices=[
                            ("accepted", "Accepted"),
                            ("accepted_with_conditions", "Accepted with Conditions"),
                            ("not_accepted", "Not Accepted"),
                        ],
                        help_text="Overall acceptance status of the pilot project",
                        max_length=30,
                    ),
                ),
                (
                    "completion_date",
                    models.DateField(
                        help_text="Date when the pilot project was completed"
                    ),
                ),
                (
                    "token_payment",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Token payment amount for pilot completion",
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "issues_to_resolve",
                    models.TextField(
                        blank=True, help_text="Any issues that need to be resolved"
                    ),
                ),
                (
                    "school_representative_signed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether school representative has signed",
                    ),
                ),
                (
                    "school_representative_signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When school representative signed",
                        null=True,
                    ),
                ),
                (
                    "company_representative_signed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether company representative has signed",
                    ),
                ),
                (
                    "company_representative_signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When company representative signed",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pilot Acceptance",
                "verbose_name_plural": "Pilot Acceptances",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="core_client_relatio_b52dd6_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="core_client_client__d5dcf7_idx",
        ),
        migrations.RemoveIndex(
            model_name="client",
            name="core_client_contrac_0a9eb9_idx",
        ),
        migrations.AddField(
            model_name="pilotacceptance",
            name="created_by",
            field=models.ForeignKey(
                help_text="User who created this acceptance record",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="created_pilot_acceptances",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="pilotacceptance",
            name="document_instance",
            field=models.OneToOneField(
                help_text="Document instance containing acceptance data and PDF",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pilot_acceptance_record",
                to="core.documentinstance",
            ),
        ),
        migrations.AddField(
            model_name="pilotacceptance",
            name="project",
            field=models.OneToOneField(
                help_text="The pilot project being accepted",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="pilot_acceptance",
                to="core.project",
            ),
        ),
        migrations.AddIndex(
            model_name="pilotacceptance",
            index=models.Index(
                fields=["project", "acceptance_status"],
                name="core_pilota_project_46da01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pilotacceptance",
            index=models.Index(
                fields=["acceptance_status", "completion_date"],
                name="core_pilota_accepta_120353_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="pilotacceptance",
            index=models.Index(
                fields=["created_by", "created_at"],
                name="core_pilota_created_c8e8fd_idx",
            ),
        ),
    ]
