# Generated by Django 4.2.7 on 2025-09-30 22:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_add_pilot_acceptance_model"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChangeRequest",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "request_date",
                    models.DateField(help_text="Date when the change was requested"),
                ),
                (
                    "reference_agreement",
                    models.CharField(
                        blank=True,
                        help_text="Reference to original agreement or contract",
                        max_length=255,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("under_review", "Under Review"),
                            ("impact_assessed", "Impact Assessed"),
                            ("client_decision", "Client Decision"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("implemented", "Implemented"),
                            ("closed", "Closed"),
                        ],
                        default="draft",
                        help_text="Current status of the change request",
                        max_length=20,
                    ),
                ),
                (
                    "client_decision",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("proceed", "Proceed with Change"),
                            ("defer", "Defer Change"),
                            ("withdraw", "Withdraw Change"),
                        ],
                        help_text="Client's decision on the change request",
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "client_rep_signed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether client representative has signed",
                    ),
                ),
                (
                    "client_rep_signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When client representative signed",
                        null=True,
                    ),
                ),
                (
                    "provider_signed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether provider representative has signed",
                    ),
                ),
                (
                    "provider_signed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When provider representative signed",
                        null=True,
                    ),
                ),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who assessed the change request impact",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assessed_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this change request",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_change_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_instance",
                    models.OneToOneField(
                        help_text="Document instance containing change request data and PDF",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_request_record",
                        to="core.documentinstance",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The pilot project this change request belongs to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="change_requests",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "verbose_name": "Change Request",
                "verbose_name_plural": "Change Requests",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="core_change_project_1c6d70_idx",
                    ),
                    models.Index(
                        fields=["status", "request_date"],
                        name="core_change_status_e5b5a7_idx",
                    ),
                    models.Index(
                        fields=["created_by", "created_at"],
                        name="core_change_created_e4f4f7_idx",
                    ),
                    models.Index(
                        fields=["assessed_by", "status"],
                        name="core_change_assesse_7094a7_idx",
                    ),
                ],
            },
        ),
    ]
