# Generated by Django 4.2.7 on 2025-10-01 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_changerequest"),
    ]

    operations = [
        migrations.CreateModel(
            name="PilotHandover",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "expected_delivery_date",
                    models.DateField(
                        help_text="Expected delivery date for the handover"
                    ),
                ),
                (
                    "assigned_team_members",
                    models.JSONField(
                        default=list,
                        help_text="List of team members assigned to this handover",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("ready_for_review", "Ready for Review"),
                            ("approved", "Approved"),
                            ("hold", "Hold"),
                            ("completed", "Completed"),
                        ],
                        default="draft",
                        help_text="Current status of the handover process",
                        max_length=20,
                    ),
                ),
                (
                    "final_go_no_go",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("approved", "Approved - Ready for Handover"),
                            ("hold", "Hold - Issues to Resolve"),
                        ],
                        help_text="Final go/no-go decision for handover",
                        max_length=10,
                        null=True,
                    ),
                ),
                (
                    "team_lead_signed",
                    models.BooleanField(
                        default=False,
                        help_text="Whether team lead has signed off on the handover",
                    ),
                ),
                (
                    "team_lead_signed_at",
                    models.DateTimeField(
                        blank=True, help_text="When team lead signed off", null=True
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        help_text="User who created this handover record",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_pilot_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "document_instance",
                    models.OneToOneField(
                        help_text="Document instance containing handover data and PDF",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pilot_handover_record",
                        to="core.documentinstance",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="The pilot project being handed over",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pilot_handovers",
                        to="core.project",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who reviewed this handover",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_pilot_handovers",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Pilot Handover",
                "verbose_name_plural": "Pilot Handovers",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "status"],
                        name="core_piloth_project_2cd540_idx",
                    ),
                    models.Index(
                        fields=["status", "expected_delivery_date"],
                        name="core_piloth_status_21b01b_idx",
                    ),
                    models.Index(
                        fields=["created_by", "created_at"],
                        name="core_piloth_created_84de13_idx",
                    ),
                    models.Index(
                        fields=["reviewed_by", "status"],
                        name="core_piloth_reviewe_58205b_idx",
                    ),
                ],
            },
        ),
    ]
