# Generated by Django 4.2.7 on 2025-10-01 06:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_pilothandover"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Uploaded file with unified storage",
                        upload_to="attachments/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "bmp",
                                    "webp",
                                    "svg",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "rtf",
                                    "odt",
                                    "xls",
                                    "xlsx",
                                    "csv",
                                    "ods",
                                    "ppt",
                                    "pptx",
                                    "odp",
                                    "zip",
                                    "rar",
                                    "7z",
                                    "tar",
                                    "gz",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_name",
                    models.CharField(
                        help_text="Original filename of the uploaded file",
                        max_length=255,
                    ),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[
                            ("image", "Image Files"),
                            ("pdf", "PDF Documents"),
                            ("document", "Document Files"),
                            ("spreadsheet", "Spreadsheet Files"),
                            ("presentation", "Presentation Files"),
                            ("archive", "Archive Files"),
                            ("other", "Other Files"),
                        ],
                        help_text="Categorized file type for filtering and validation",
                        max_length=50,
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(help_text="File size in bytes"),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, help_text="MIME type of the file", max_length=100
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Optional description of the file"
                    ),
                ),
                (
                    "download_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of times this file has been downloaded",
                    ),
                ),
                (
                    "last_downloaded_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="When this file was last downloaded",
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this file is active and accessible",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        help_text="Project this file is attached to",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="core.project",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        help_text="User who uploaded this file",
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="uploaded_attachments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Attachment",
                "verbose_name_plural": "Attachments",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["project", "created_at"],
                        name="core_attach_project_95c4f8_idx",
                    ),
                    models.Index(
                        fields=["uploaded_by", "created_at"],
                        name="core_attach_uploade_a2cd44_idx",
                    ),
                    models.Index(
                        fields=["file_type", "created_at"],
                        name="core_attach_file_ty_65de18_idx",
                    ),
                    models.Index(
                        fields=["is_active", "created_at"],
                        name="core_attach_is_acti_4d918a_idx",
                    ),
                ],
            },
        ),
    ]
